<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\AppBundle\Controller\HomePageController' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Controller/HomePageController.php';

return $this->services['App\AppBundle\Controller\HomePageController'] = new \App\AppBundle\Controller\HomePageController(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load(__DIR__.'/getTemplatingService.php')) && false ?: '_'});
