<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ69r4jv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ69r4jv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQ69r4jv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQ69r4jv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQ69r4jv\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Q69r4jv',
    'container.build_id' => 'dc7a5e92',
    'container.build_time' => 1517337201,
));
